# Generated by Django 5.0.1 on 2024-01-09 02:49

import datetime
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "В обработке"), (1, "Одобрено"), (2, "Отклонено")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Дата проведения",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Web of Science/Scopus"),
                            (2, "ВАК"),
                            (3, "РИНЦ"),
                            (4, "Остальное"),
                        ],
                        default=4,
                        verbose_name="Тип публикации",
                    ),
                ),
                ("url", models.URLField(verbose_name="Ссылка")),
                (
                    "count_coauthors",
                    models.IntegerField(default=0, verbose_name="Количество соавторов"),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
        migrations.CreateModel(
            name="Olympiad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "В обработке"), (1, "Одобрено"), (2, "Отклонено")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Дата проведения",
                    ),
                ),
                (
                    "place",
                    models.IntegerField(
                        choices=[
                            (1, "🥇Первое"),
                            (2, "🥈Второе"),
                            (3, "🥉Третье"),
                            (4, "Участник"),
                        ],
                        default=4,
                        verbose_name="Занятое место",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Международный"),
                            (2, "Всероссийский"),
                            (3, "Ведомственный"),
                            (4, "Региональный"),
                        ],
                        default=4,
                        verbose_name="Уровень олимпиады",
                    ),
                ),
            ],
            options={
                "verbose_name": "Олимпиада",
                "verbose_name_plural": "Олимпиады",
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "В обработке"), (1, "Одобрено"), (2, "Отклонено")],
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="Дата проведения",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Патент на изобретение, свидетельство"),
                            (2, "Патент на полезную модель"),
                            (3, "Заявка"),
                        ],
                        default=1,
                        verbose_name="Тип патента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Патент",
                "verbose_name_plural": "Патенты",
            },
        ),
    ]
