# Generated by Django 5.0.1 on 2024-01-09 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievement", "0001_initial"),
        ("comment", "0001_initial"),
        ("document", "0001_initial"),
        ("statement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="comments",
            field=models.ManyToManyField(blank=True, to="comment.comment"),
        ),
        migrations.AddField(
            model_name="article",
            name="documents",
            field=models.ManyToManyField(blank=True, to="document.document"),
        ),
        migrations.AddField(
            model_name="article",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="statement.statement",
            ),
        ),
        migrations.AddField(
            model_name="olympiad",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="olympiad",
            name="comments",
            field=models.ManyToManyField(blank=True, to="comment.comment"),
        ),
        migrations.AddField(
            model_name="olympiad",
            name="documents",
            field=models.ManyToManyField(blank=True, to="document.document"),
        ),
        migrations.AddField(
            model_name="olympiad",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="statement.statement",
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="comments",
            field=models.ManyToManyField(blank=True, to="comment.comment"),
        ),
        migrations.AddField(
            model_name="patent",
            name="documents",
            field=models.ManyToManyField(blank=True, to="document.document"),
        ),
        migrations.AddField(
            model_name="patent",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="statement.statement",
            ),
        ),
    ]
