# Generated by Django 5.0.1 on 2024-01-09 02:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name='ID',
                    ),
                ),
                ('file', models.FileField(upload_to='documents')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
